version: '3.9'
services:
  # PHP-FPM Service
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $APP_VOLUMES_SRC:/var/www/html
    env_file:
      - .env
    depends_on:
      - mysql-db
    networks:
      - qr_app_network

  # NGINX Service
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - $APP_VOLUMES_SRC:/var/www/html 
    ports:
      - "$NGINX_PORT:80"
    depends_on:
      - php-fpm  
      - mysql-db 
    networks:
      - qr_app_network

  # MySQL Database Service
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: php-app
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASS
    ports:
      - "3308:3306"
    networks:
      - qr_app_network 

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      UPLOAD_LIMIT: 1000000000

    restart: always
    ports:
      - 8081:80
    networks:
      - qr_app_network

  #Mail services
  # mail-app:
  #   build: 
  #     context: ../mail/vendor/laravel/sail/runtimes/8.3
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8083:80" 
  #   networks:
  #     - qr_app_network

  #Scanned.page Services
  sacnned-page:
    build:
      context: ../test-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    networks:
      - qr_app_network

networks:
    qr_app_network:
        external: true
