version: '3.9'
services:
  # PHP-FPM Service
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $APP_VOLUMES_SRC:/var/www/html
    env_file:
      - .env
    depends_on:
      - mysql-db
    networks:
      - qr_app_network

  # NGINX Service
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - $APP_VOLUMES_SRC:/var/www/html 
    ports:
      - "$NGINX_PORT:80"
    depends_on:
      - php-fpm  
      - mysql-db 
    networks:
      - qr_app_network

  # MySQL Database Service
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "$MYSQL_PORT:3306"
    networks:
      - qr_app_network 

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db 
    ports:
      - "8081:80" 
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - qr_app_network

  #Mail services
  # mail-app:
  #   build: 
  #     context: /media/rightmo/Others/Project/docker/mail/vendor/laravel/sail/runtimes/8.3
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8083:80" 
  #   networks:
  #     - qr_app_network


networks:
    qr_app_network:
        external: true
